In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Kaggle Practice - Digital Skola Batch 11

by: Ari Sulistiyo Prabowo
____

**Contents:**
- Data Preparation 
    - Reading dataset
    - Check any null values
    - Check data type in each columns
- Data Cleansing
    - Handling null values
    - Delete any duplicate values
    - Change the data type if there is any wrong data type
- Exploratory Data Analysis
    - Show the distribution in each columns
        - add mean, median, mode in each columns (untuk liat skewness/kemiringan)

## Data Preparation

In [47]:
# import library
import pandas as pd
import numpy as np

# import visualization library
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# reading dataset
data = pd.read_csv("../input/water-potability/water_potability.csv")
data.head()

In [27]:
check_null = pd.DataFrame(data.dtypes).T.rename({0: "Column Type"})
check_null = check_null.append(pd.DataFrame(data.isnull().sum()).T.rename({0:'Number of Null Values'}))
check_null = check_null.append(pd.DataFrame(round(data.isnull().sum()/data.shape[0]*100)).T.rename({0:"Percentage of Null Values"}))
check_null

There are null values in several columns such as:
- pH (15%)
- Sulfate (24%)
- Trihalomethanes (5%)

From this null values, we can do a data cleansing either to drop all null values or we fill null values with the certain conditions

## Data Cleansing

In [25]:
# Handling null values by dropping the null values
data_v1 = data.dropna()
data_v1.shape

In [33]:
# Is there any duplicate values?
data_v1 = data_v1.drop_duplicates()
data_v1.shape

In [45]:
# example to change the data type
a = data_v1.copy()
a['Potability'] = a['Potability'].astype("object")
a.info()

In this data, we have new variable called **data_v1** which already dropped the null values and duplicate values. In terms of data type, there is no column that contains wrong data type

## Exploratory Data Analysis

In [53]:
# create function to visualize the data without new code
def histogram(x):
    """
    this function is to show the distribution of data
    """
    plt.hist(data[x])
    plt.show()

In [55]:
histogram(x="Conductivity")

In [57]:
histogram(x="Organic_carbon")

In [59]:
#simple plot
sns.kdeplot(data=data_v1, x='Organic_carbon')
plt.show()

In [62]:
# create function to show the density of the data in distribution
columns = ['ph', 'Hardness', 'Solids', 'Chloramines', 'Sulfate', 'Conductivity',
       'Organic_carbon', 'Trihalomethanes', 'Turbidity']

fig, axes = plt.subplots(3, 3, figsize=(12,10))
axes = [ax for axes_row in axes for ax in axes_row]

for i, col in enumerate(columns):
    plot = sns.kdeplot(data=data_v1, x=col, ax=axes[i])
plt.tight_layout()