#**Advanced Dataframe**

created by Ari Sulistiyo Prabowo


This notebook is created to teach student about dataframe advanced level. All the code is free to reuse by everyone.

**Contents**
1. Indexing Dataframe
2. Dropping Variable/Column
3. Joining Dataframe
4. Concatenate & Append Dataframe
5. Pivot Table Dataframe
6. Melting Dataframe
7. Fungsi Lambda dalam Dataframe

___

In [ ]:
#import library
import pandas as pd
import numpy as np

import plotly.express as px
import matplotlib.pyplot as plt

In [ ]:
data = pd.read_csv("https://raw.githubusercontent.com/densaiko/data_science_learning/main/dataset/insurance.csv")
data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

### Indexing Dataframe

In [ ]:
random_ = data.sample(n=10)
random_.head()

      age     sex    bmi  children smoker     region      charges
1308   25  female  30.20         0    yes  southwest  33900.65300
221    53  female  33.25         0     no  northeast  10564.88450
989    24  female  20.52         0    yes  northeast  14571.89080
839    59  female  31.35         0     no  northwest  12622.17950
354    18  female  38.28         0     no  southeast  14133.03775

In [ ]:
## reset index starting from 0
random_.reset_index(drop=True)

   age     sex     bmi  children smoker     region      charges
0   25  female  30.200         0    yes  southwest  33900.65300
1   53  female  33.250         0     no  northeast  10564.88450
2   24  female  20.520         0    yes  northeast  14571.89080
3   59  female  31.350         0     no  northwest  12622.17950
4   18  female  38.280         0     no  southeast  14133.03775
5   57    male  40.370         0     no  southeast  10982.50130
6   40    male  34.105         1     no  northeast   6600.20595
7   50  female  27.600         1    yes  southwest  24520.26400
8   35    male  24.130         1     no  northwest   5125.21570
9   50  female  23.540         2     no  southeast  10107.22060

In [ ]:
## set column as index
random_.set_index('age')

        sex     bmi  children smoker     region      charges
age
25   female  30.200         0    yes  southwest  33900.65300
53   female  33.250         0     no  northeast  10564.88450
24   female  20.520         0    yes  northeast  14571.89080
59   female  31.350         0     no  northwest  12622.17950
18   female  38.280         0     no  southeast  14133.03775
57     male  40.370         0     no  southeast  10982.50130
40     male  34.105         1     no  northeast   6600.20595
50   female  27.600         1    yes  southwest  24520.26400
35     male  24.130         1     no  northwest   5125.21570
50   female  23.540         2     no  southeast  10107.22060

### Dropping Variable/Column

In [ ]:
# dropping column
data.drop(['bmi','children'], axis=1).head()

   age     sex smoker     region      charges
0   19  female    yes  southwest  16884.92400
1   18    male     no  southeast   1725.55230
2   28    male     no  southeast   4449.46200
3   33    male     no  northwest  21984.47061
4   32    male     no  northwest   3866.85520

### Joining Dataframe

In [ ]:
data_dummy = data.iloc[:3,0:2]
data_dummy

   age     sex
0   19  female
1   18    male
2   28    male

In [ ]:
data_5 = data.loc[:4,["age","bmi"]]
data_5

   age     bmi
0   19  27.900
1   18  33.770
2   28  33.000
3   33  22.705
4   32  28.880

In [ ]:
data_5.join(data_dummy, lsuffix='_first', rsuffix='_second')

   age_first     bmi  age_second     sex
0         19  27.900        19.0  female
1         18  33.770        18.0    male
2         28  33.000        28.0    male
3         33  22.705         NaN     NaN
4         32  28.880         NaN     NaN

### Concatenate & Append Dataframe

In [ ]:
# concatenate data in horizontal
pd.concat([data_dummy,data_5], axis=1)

    age     sex  age     bmi
0  19.0  female   19  27.900
1  18.0    male   18  33.770
2  28.0    male   28  33.000
3   NaN     NaN   33  22.705
4   NaN     NaN   32  28.880

In [ ]:
# concatenate data in vertical
pd.concat([data_dummy,data_5], axis=0)

   age     sex     bmi
0   19  female     NaN
1   18    male     NaN
2   28    male     NaN
0   19     NaN  27.900
1   18     NaN  33.770
2   28     NaN  33.000
3   33     NaN  22.705
4   32     NaN  28.880

In [ ]:
# append data
data_5.append(data_dummy)

   age     bmi     sex
0   19  27.900     NaN
1   18  33.770     NaN
2   28  33.000     NaN
3   33  22.705     NaN
4   32  28.880     NaN
0   19     NaN  female
1   18     NaN    male
2   28     NaN    male

### Pivot Table Dataframe

In [ ]:
# pivot table
pd.pivot_table(data, values="bmi", index=["sex","smoker"], columns="region", 
               aggfunc=np.sum)

region         northeast  northwest  southeast  southwest
sex    smoker
female no       3930.625   3980.975    4556.42     4237.1
       yes       790.590    820.610    1161.05      632.7
male   no       3607.720   3818.810    4573.36     3908.5
       yes      1123.280    869.535    1850.75     1165.6

In [ ]:
# pivot table
pd.pivot_table(data, values="bmi", index=["sex","smoker"], columns="region", 
               aggfunc=np.max)

region         northeast  northwest  southeast  southwest
sex    smoker
female no         48.070     42.940      46.75       46.7
       yes        42.750     38.950      47.41       47.6
male   no         42.655     41.325      53.13       45.9
       yes        41.895     40.565      52.58       39.9

### Melting Dataframe

In [ ]:
data_melt = data.iloc[:5,:3]
data_melt

   age     sex     bmi
0   19  female  27.900
1   18    male  33.770
2   28    male  33.000
3   33    male  22.705
4   32    male  28.880

In [ ]:
pd.melt(data_melt, id_vars=["sex"], value_vars=["age"])

      sex variable  value
0  female      age     19
1    male      age     18
2    male      age     28
3    male      age     33
4    male      age     32

In [ ]:
data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
female = data[data["sex"] == "female"]
male = data[data['sex'] == "male"]

In [ ]:
#Summing the region in each sex
female_se=(female['region']=='southeast').sum()
female_sw=(female['region']=='southwest').sum()
female_nw=(female['region']=='northwest').sum()
female_ne=(female['region']=='northeast').sum()

#Summing the region in each sex
male_se=(male['region']=='southeast').sum()
male_sw=(male['region']=='southwest').sum()
male_nw=(male['region']=='northwest').sum()
male_ne=(male['region']=='northeast').sum()

In [ ]:
dict_data = [{'Sex':"Male", "southeast":male_se, "southwest":male_sw,\
              "northwest":male_nw, "northeast":male_ne},
             {'Sex':"Female", "southeast":female_se, "southwest":female_sw,\
              "northwest":female_nw, "northeast":female_ne}]

data_sex = pd.DataFrame(dict_data)
data_sex

      Sex  southeast  southwest  northwest  northeast
0    Male        189        163        161        163
1  Female        175        162        164        161

In [ ]:
data_sex_melt = data_sex.melt(id_vars="Sex", value_vars=['southeast','southwest','northwest','northeast'])
data_sex_melt

      Sex   variable  value
0    Male  southeast    189
1  Female  southeast    175
2    Male  southwest    163
3  Female  southwest    162
4    Male  northwest    161
5  Female  northwest    164
6    Male  northeast    163
7  Female  northeast    161

In [ ]:
data_sex_m = data_sex_melt[data_sex_melt["Sex"] == "Male"]

#color palette
ylw = '#fcd12a' # cases - yellow
dth = '#ff2e63' # death - red
rec = '#21bf73' # recovered - cyan

fig=px.treemap(data_sex_m, path=['variable'], values='value', height=500, width=800, color_discrete_sequence=[ylw, dth, rec])
fig.show()

In [ ]:
data_sex_f = data_sex_melt[data_sex_melt["Sex"] == "Female"]

#color palette
ylw = '#fcd12a' # cases - yellow
dth = '#ff2e63' # death - red
rec = '#21bf73' # recovered - cyan

fig=px.treemap(data_sex_f, path=['variable'], values='value', height=500, width=800, color_discrete_sequence=[ylw, dth, rec])
fig.show()

### Fungsi Lambda dalam Dataframe

In [ ]:
# basic lambda
test = lambda a: a*3
test(10)

30

In [ ]:
# create new variables/columns
curila = []

for i in data['bmi']:
  if i < 26:
    curila.append("Low BMI")
  else:
    curila.append("High BMI")

data_lambda = data.copy()
data_lambda['bmi_category'] = curila
data_lambda.head()

   age     sex     bmi  children smoker     region      charges bmi_category
0   19  female  27.900         0    yes  southwest  16884.92400     High BMI
1   18    male  33.770         1     no  southeast   1725.55230     High BMI
2   28    male  33.000         3     no  southeast   4449.46200     High BMI
3   33    male  22.705         0     no  northwest  21984.47061      Low BMI
4   32    male  28.880         0     no  northwest   3866.85520     High BMI

In [ ]:
data["bmi_category_lambda"] = data['bmi'].apply(lambda x: "Low BMI" if x < 30 else "High BMI")
data.head()

   age     sex     bmi  ...     region      charges bmi_category_lambda
0   19  female  27.900  ...  southwest  16884.92400             Low BMI
1   18    male  33.770  ...  southeast   1725.55230            High BMI
2   28    male  33.000  ...  southeast   4449.46200            High BMI
3   33    male  22.705  ...  northwest  21984.47061             Low BMI
4   32    male  28.880  ...  northwest   3866.85520             Low BMI

[5 rows x 8 columns]